/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'savingsOut' : IDL.Null,
  'cashOut' : IDL.Null,
  'upiOut' : IDL.Null,
  'upiIn' : IDL.Null,
  'cashIn' : IDL.Null,
  'deductionsOut' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FilterDailyStats = IDL.Record({
  'date' : IDL.Int,
  'userAmountDeduction' : IDL.Nat,
  'totalTransaction' : IDL.Nat,
  'upiIn' : IDL.Nat,
  'cashIn' : IDL.Nat,
  'tenPercentDeduction' : IDL.Nat,
});
export const OpeningBalance = IDL.Record({
  'date' : IDL.Int,
  'upiBalance' : IDL.Nat,
  'cashBalance' : IDL.Nat,
  'savings' : IDL.Nat,
  'userDeductions' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Balance = IDL.Record({
  'savingsBalance' : IDL.Int,
  'deductionsBalance' : IDL.Int,
  'cashOut' : IDL.Nat,
  'upiOut' : IDL.Nat,
  'upiBalance' : IDL.Int,
  'cashBalance' : IDL.Int,
  'upiIn' : IDL.Nat,
  'cashIn' : IDL.Nat,
  'totalBalance' : IDL.Int,
  'excludedTotalBalance' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CumulativeStats = IDL.Record({
  'cumulativeUserSpecifiedDeductions' : IDL.Nat,
  'cumulativeTenPercentSavings' : IDL.Nat,
});
export const DailyTracking = IDL.Record({
  'totalDailyTransactionsWithDeduction' : IDL.Int,
  'dailyTenPercentDeduction' : IDL.Nat,
  'totalDailyTransactions' : IDL.Nat,
  'userSpecifiedDailyDeduction' : IDL.Nat,
});
export const DaywiseTransactionStats = IDL.Record({
  'combinedTotal' : IDL.Nat,
  'cashOut' : IDL.Nat,
  'totalBalanceForDay' : IDL.Int,
  'upiOut' : IDL.Nat,
  'upiIn' : IDL.Nat,
  'cashIn' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
});
export const MonthlyTransactionSummary = IDL.Record({
  'totalAmount' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
  'transactionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addOpeningBalance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
      [IDL.Text],
      [],
    ),
  'addTransaction' : IDL.Func(
      [TransactionType, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearTransactionData' : IDL.Func([], [IDL.Text], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'editTransaction' : IDL.Func(
      [IDL.Nat, TransactionType, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Text],
      [],
    ),
  'filterBalanceByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(FilterDailyStats)],
      ['query'],
    ),
  'getAllOpeningBalances' : IDL.Func([], [IDL.Vec(OpeningBalance)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBalances' : IDL.Func([], [Balance], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCumulativeStats' : IDL.Func([], [CumulativeStats], ['query']),
  'getDailyTracking' : IDL.Func([IDL.Int], [DailyTracking], ['query']),
  'getDaywiseTransactions' : IDL.Func(
      [IDL.Int],
      [DaywiseTransactionStats],
      ['query'],
    ),
  'getMonthlyTransactions' : IDL.Func(
      [IDL.Int, IDL.Int, TransactionType],
      [MonthlyTransactionSummary],
      ['query'],
    ),
  'getOpeningBalance' : IDL.Func([], [OpeningBalance], ['query']),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSpecifiedDeduction' : IDL.Func([IDL.Int], [IDL.Nat], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAnonymous' : IDL.Func([], [IDL.Bool], ['query']),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserSpecifiedDeduction' : IDL.Func([IDL.Int, IDL.Nat], [], []),
  'updateOpeningBalance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'savingsOut' : IDL.Null,
    'cashOut' : IDL.Null,
    'upiOut' : IDL.Null,
    'upiIn' : IDL.Null,
    'cashIn' : IDL.Null,
    'deductionsOut' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FilterDailyStats = IDL.Record({
    'date' : IDL.Int,
    'userAmountDeduction' : IDL.Nat,
    'totalTransaction' : IDL.Nat,
    'upiIn' : IDL.Nat,
    'cashIn' : IDL.Nat,
    'tenPercentDeduction' : IDL.Nat,
  });
  const OpeningBalance = IDL.Record({
    'date' : IDL.Int,
    'upiBalance' : IDL.Nat,
    'cashBalance' : IDL.Nat,
    'savings' : IDL.Nat,
    'userDeductions' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Balance = IDL.Record({
    'savingsBalance' : IDL.Int,
    'deductionsBalance' : IDL.Int,
    'cashOut' : IDL.Nat,
    'upiOut' : IDL.Nat,
    'upiBalance' : IDL.Int,
    'cashBalance' : IDL.Int,
    'upiIn' : IDL.Nat,
    'cashIn' : IDL.Nat,
    'totalBalance' : IDL.Int,
    'excludedTotalBalance' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CumulativeStats = IDL.Record({
    'cumulativeUserSpecifiedDeductions' : IDL.Nat,
    'cumulativeTenPercentSavings' : IDL.Nat,
  });
  const DailyTracking = IDL.Record({
    'totalDailyTransactionsWithDeduction' : IDL.Int,
    'dailyTenPercentDeduction' : IDL.Nat,
    'totalDailyTransactions' : IDL.Nat,
    'userSpecifiedDailyDeduction' : IDL.Nat,
  });
  const DaywiseTransactionStats = IDL.Record({
    'combinedTotal' : IDL.Nat,
    'cashOut' : IDL.Nat,
    'totalBalanceForDay' : IDL.Int,
    'upiOut' : IDL.Nat,
    'upiIn' : IDL.Nat,
    'cashIn' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
  });
  const MonthlyTransactionSummary = IDL.Record({
    'totalAmount' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
    'transactionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addOpeningBalance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
        [IDL.Text],
        [],
      ),
    'addTransaction' : IDL.Func(
        [TransactionType, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearTransactionData' : IDL.Func([], [IDL.Text], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'editTransaction' : IDL.Func(
        [
          IDL.Nat,
          TransactionType,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Text],
        [],
      ),
    'filterBalanceByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(FilterDailyStats)],
        ['query'],
      ),
    'getAllOpeningBalances' : IDL.Func(
        [],
        [IDL.Vec(OpeningBalance)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBalances' : IDL.Func([], [Balance], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCumulativeStats' : IDL.Func([], [CumulativeStats], ['query']),
    'getDailyTracking' : IDL.Func([IDL.Int], [DailyTracking], ['query']),
    'getDaywiseTransactions' : IDL.Func(
        [IDL.Int],
        [DaywiseTransactionStats],
        ['query'],
      ),
    'getMonthlyTransactions' : IDL.Func(
        [IDL.Int, IDL.Int, TransactionType],
        [MonthlyTransactionSummary],
        ['query'],
      ),
    'getOpeningBalance' : IDL.Func([], [OpeningBalance], ['query']),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSpecifiedDeduction' : IDL.Func([IDL.Int], [IDL.Nat], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAnonymous' : IDL.Func([], [IDL.Bool], ['query']),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserSpecifiedDeduction' : IDL.Func([IDL.Int, IDL.Nat], [], []),
    'updateOpeningBalance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };