/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Balance {
  'savingsBalance' : bigint,
  'deductionsBalance' : bigint,
  'cashOut' : bigint,
  'upiOut' : bigint,
  'upiBalance' : bigint,
  'cashBalance' : bigint,
  'upiIn' : bigint,
  'cashIn' : bigint,
  'totalBalance' : bigint,
  'excludedTotalBalance' : bigint,
}
export interface CumulativeStats {
  'cumulativeUserSpecifiedDeductions' : bigint,
  'cumulativeTenPercentSavings' : bigint,
}
export interface DailyTracking {
  'totalDailyTransactionsWithDeduction' : bigint,
  'dailyTenPercentDeduction' : bigint,
  'totalDailyTransactions' : bigint,
  'userSpecifiedDailyDeduction' : bigint,
}
export interface DaywiseTransactionStats {
  'combinedTotal' : bigint,
  'cashOut' : bigint,
  'totalBalanceForDay' : bigint,
  'upiOut' : bigint,
  'upiIn' : bigint,
  'cashIn' : bigint,
  'transactions' : Array<Transaction>,
}
export interface FilterDailyStats {
  'date' : bigint,
  'userAmountDeduction' : bigint,
  'totalTransaction' : bigint,
  'upiIn' : bigint,
  'cashIn' : bigint,
  'tenPercentDeduction' : bigint,
}
export interface MonthlyTransactionSummary {
  'totalAmount' : bigint,
  'transactions' : Array<Transaction>,
  'transactionCount' : bigint,
}
export interface OpeningBalance {
  'date' : bigint,
  'upiBalance' : bigint,
  'cashBalance' : bigint,
  'savings' : bigint,
  'userDeductions' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'date' : bigint,
  'description' : string,
  'amount' : bigint,
}
export type TransactionType = { 'savingsOut' : null } |
  { 'cashOut' : null } |
  { 'upiOut' : null } |
  { 'upiIn' : null } |
  { 'cashIn' : null } |
  { 'deductionsOut' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addOpeningBalance' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    string
  >,
  'addTransaction' : ActorMethod<
    [TransactionType, bigint, [] | [string], [] | [bigint]],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearTransactionData' : ActorMethod<[], string>,
  'deleteTransaction' : ActorMethod<[bigint], string>,
  'editTransaction' : ActorMethod<
    [bigint, TransactionType, bigint, [] | [string], [] | [bigint]],
    string
  >,
  'filterBalanceByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<FilterDailyStats>
  >,
  'getAllOpeningBalances' : ActorMethod<[], Array<OpeningBalance>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBalances' : ActorMethod<[], Balance>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCumulativeStats' : ActorMethod<[], CumulativeStats>,
  'getDailyTracking' : ActorMethod<[bigint], DailyTracking>,
  'getDaywiseTransactions' : ActorMethod<[bigint], DaywiseTransactionStats>,
  'getMonthlyTransactions' : ActorMethod<
    [bigint, bigint, TransactionType],
    MonthlyTransactionSummary
  >,
  'getOpeningBalance' : ActorMethod<[], OpeningBalance>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSpecifiedDeduction' : ActorMethod<[bigint], bigint>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAnonymous' : ActorMethod<[], boolean>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserSpecifiedDeduction' : ActorMethod<[bigint, bigint], undefined>,
  'updateOpeningBalance' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];