/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    id: bigint;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
}
export interface DaywiseTransactionStats {
    combinedTotal: bigint;
    cashOut: bigint;
    totalBalanceForDay: bigint;
    upiOut: bigint;
    upiIn: bigint;
    cashIn: bigint;
    transactions: Array<Transaction>;
}
export interface DailyTracking {
    totalDailyTransactionsWithDeduction: bigint;
    dailyTenPercentDeduction: bigint;
    totalDailyTransactions: bigint;
    userSpecifiedDailyDeduction: bigint;
}
export interface FilterDailyStats {
    date: bigint;
    userAmountDeduction: bigint;
    totalTransaction: bigint;
    upiIn: bigint;
    cashIn: bigint;
    tenPercentDeduction: bigint;
}
export interface Balance {
    savingsBalance: bigint;
    deductionsBalance: bigint;
    cashOut: bigint;
    upiOut: bigint;
    upiBalance: bigint;
    cashBalance: bigint;
    upiIn: bigint;
    cashIn: bigint;
    totalBalance: bigint;
    excludedTotalBalance: bigint;
}
export interface CumulativeStats {
    cumulativeUserSpecifiedDeductions: bigint;
    cumulativeTenPercentSavings: bigint;
}
export interface OpeningBalance {
    date: bigint;
    upiBalance: bigint;
    cashBalance: bigint;
    savings: bigint;
    userDeductions: bigint;
}
export interface UserProfile {
    name: string;
}
export interface MonthlyTransactionSummary {
    totalAmount: bigint;
    transactions: Array<Transaction>;
    transactionCount: bigint;
}
export enum TransactionType {
    savingsOut = "savingsOut",
    cashOut = "cashOut",
    upiOut = "upiOut",
    upiIn = "upiIn",
    cashIn = "cashIn",
    deductionsOut = "deductionsOut"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addOpeningBalance(cashBalance: bigint, upiBalance: bigint, savings: bigint, userDeductions: bigint, date: bigint): Promise<string>;
    addTransaction(transactionType: TransactionType, amount: bigint, description: string | null, date: bigint | null): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearTransactionData(): Promise<string>;
    deleteTransaction(id: bigint): Promise<string>;
    editTransaction(transactionId: bigint, transactionType: TransactionType, amount: bigint, description: string | null, date: bigint | null): Promise<string>;
    filterBalanceByDateRange(startDate: bigint, endDate: bigint): Promise<Array<FilterDailyStats>>;
    getAllOpeningBalances(): Promise<Array<OpeningBalance>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBalances(): Promise<Balance>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCumulativeStats(): Promise<CumulativeStats>;
    getDailyTracking(date: bigint): Promise<DailyTracking>;
    getDaywiseTransactions(date: bigint): Promise<DaywiseTransactionStats>;
    getMonthlyTransactions(year: bigint, month: bigint, transactionType: TransactionType): Promise<MonthlyTransactionSummary>;
    getOpeningBalance(): Promise<OpeningBalance>;
    getTransactionsByType(transactionType: TransactionType): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSpecifiedDeduction(date: bigint): Promise<bigint>;
    initializeAccessControl(): Promise<void>;
    isAnonymous(): Promise<boolean>;
    isAuthenticated(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserSpecifiedDeduction(date: bigint, amount: bigint): Promise<void>;
    updateOpeningBalance(cashBalance: bigint, upiBalance: bigint, savings: bigint, userDeductions: bigint, date: bigint): Promise<string>;
}
import type { DaywiseTransactionStats as _DaywiseTransactionStats, MonthlyTransactionSummary as _MonthlyTransactionSummary, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOpeningBalance(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOpeningBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOpeningBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTransaction(arg0: TransactionType, arg1: bigint, arg2: string | null, arg3: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearTransactionData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTransactionData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTransactionData();
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async editTransaction(arg0: bigint, arg1: TransactionType, arg2: bigint, arg3: string | null, arg4: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.editTransaction(arg0, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTransaction(arg0, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async filterBalanceByDateRange(arg0: bigint, arg1: bigint): Promise<Array<FilterDailyStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBalanceByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBalanceByDateRange(arg0, arg1);
            return result;
        }
    }
    async getAllOpeningBalances(): Promise<Array<OpeningBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpeningBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpeningBalances();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalances(): Promise<Balance> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalances();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCumulativeStats(): Promise<CumulativeStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCumulativeStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCumulativeStats();
            return result;
        }
    }
    async getDailyTracking(arg0: bigint): Promise<DailyTracking> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTracking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTracking(arg0);
            return result;
        }
    }
    async getDaywiseTransactions(arg0: bigint): Promise<DaywiseTransactionStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDaywiseTransactions(arg0);
                return from_candid_DaywiseTransactionStats_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDaywiseTransactions(arg0);
            return from_candid_DaywiseTransactionStats_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyTransactions(arg0: bigint, arg1: bigint, arg2: TransactionType): Promise<MonthlyTransactionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyTransactions(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_MonthlyTransactionSummary_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyTransactions(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_MonthlyTransactionSummary_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpeningBalance(): Promise<OpeningBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpeningBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpeningBalance();
            return result;
        }
    }
    async getTransactionsByType(arg0: TransactionType): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSpecifiedDeduction(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSpecifiedDeduction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSpecifiedDeduction(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAnonymous(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAnonymous();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAnonymous();
            return result;
        }
    }
    async isAuthenticated(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticated();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setUserSpecifiedDeduction(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserSpecifiedDeduction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserSpecifiedDeduction(arg0, arg1);
            return result;
        }
    }
    async updateOpeningBalance(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpeningBalance(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpeningBalance(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_DaywiseTransactionStats_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaywiseTransactionStats): DaywiseTransactionStats {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MonthlyTransactionSummary_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MonthlyTransactionSummary): MonthlyTransactionSummary {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    combinedTotal: bigint;
    cashOut: bigint;
    totalBalanceForDay: bigint;
    upiOut: bigint;
    upiIn: bigint;
    cashIn: bigint;
    transactions: Array<_Transaction>;
}): {
    combinedTotal: bigint;
    cashOut: bigint;
    totalBalanceForDay: bigint;
    upiOut: bigint;
    upiIn: bigint;
    cashIn: bigint;
    transactions: Array<Transaction>;
} {
    return {
        combinedTotal: value.combinedTotal,
        cashOut: value.cashOut,
        totalBalanceForDay: value.totalBalanceForDay,
        upiOut: value.upiOut,
        upiIn: value.upiIn,
        cashIn: value.cashIn,
        transactions: from_candid_vec_n7(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAmount: bigint;
    transactions: Array<_Transaction>;
    transactionCount: bigint;
}): {
    totalAmount: bigint;
    transactions: Array<Transaction>;
    transactionCount: bigint;
} {
    return {
        totalAmount: value.totalAmount,
        transactions: from_candid_vec_n7(_uploadFile, _downloadFile, value.transactions),
        transactionCount: value.transactionCount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: _TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
}): {
    id: bigint;
    transactionType: TransactionType;
    date: bigint;
    description: string;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n10(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    savingsOut: null;
} | {
    cashOut: null;
} | {
    upiOut: null;
} | {
    upiIn: null;
} | {
    cashIn: null;
} | {
    deductionsOut: null;
}): TransactionType {
    return "savingsOut" in value ? TransactionType.savingsOut : "cashOut" in value ? TransactionType.cashOut : "upiOut" in value ? TransactionType.upiOut : "upiIn" in value ? TransactionType.upiIn : "cashIn" in value ? TransactionType.cashIn : "deductionsOut" in value ? TransactionType.deductionsOut : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TransactionType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    savingsOut: null;
} | {
    cashOut: null;
} | {
    upiOut: null;
} | {
    upiIn: null;
} | {
    cashIn: null;
} | {
    deductionsOut: null;
} {
    return value == TransactionType.savingsOut ? {
        savingsOut: null
    } : value == TransactionType.cashOut ? {
        cashOut: null
    } : value == TransactionType.upiOut ? {
        upiOut: null
    } : value == TransactionType.upiIn ? {
        upiIn: null
    } : value == TransactionType.cashIn ? {
        cashIn: null
    } : value == TransactionType.deductionsOut ? {
        deductionsOut: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
